# Site settings
title: "Big Hub Solutions"
description: "Data Solutions & Process Optimization Agency"
baseurl: ""
url: "https://www.bighubsolutions.com"
tagline: "Discover your Data. Process it, transform it, and make it valuable."

# Company info
owner:
  name: "Big Hub Solutions"
  email: "owner@bighubsolutions.com"
  linkedin_username: "big-hub-solutions"
  github_username: "big-hub"
  location: "U.S. & Colombia"

# Analytics
gtm_id: "GTM-THHDCLF"

# Build settings
markdown: kramdown
